language: go
sudo: false
go:
  - tip
before_install:
  - git clone git://github.com/rsc/pdf $GOPATH/src/rsc.io/pdf
  - go get github.com/mattn/goveralls
  - go get gonum.org/v1/plot/...
script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci