language: go
sudo: true
go:
  - tip
addons:
  apt:
    packages:
    - gfortran
before_install:
  - yum install -y hg
  - go get github.com/mattn/goveralls
  - go get gonum.org/v1/plot/...
script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci