sudo: false

language: go
addons:
  apt:
    packages:
      - mercurial
# go:
   # - master
before_install:
  - go get github.com/mattn/goveralls
  - go get -d -v gonum.org/v1/plot/...
script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci